### PR TITLE
Ignore using named colors inside sass functions

### PR DESCRIPTION
**Pull request by NickCiliak**
For example, I'd like to be able to do this:

`color: map-get($colors, white);`

See https://stylelint.io/user-guide/rules/color-named/#ignore-inside-function

### CODE REVIEW

**Comment by NickCiliak** [comment]
@ActiveCampaign/site

**Comment by rod** [comment]
@NickCiliak why `color: map-get($colors, white);` as opposed to `color: map-get($colors, $white);`?

**Comment by NickCiliak** [comment]
@rod There is no variable `$white`, it exists as a property(?) of the map `$colors`.

**Review by rod — APPROVED** [review]
🎉

**Comment by rod** [comment]
@NickCiliak I see the problem now. LGTM!

**Pull request merged**
